# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/1/BSTF_CPU_ip/RV-CCCPU.srcs/sources_1/ip/cpuclk/cpuclk.xci
# IP: The module: 'cpuclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/1/BSTF_CPU_ip/RV-CCCPU.gen/sources_1/ip/cpuclk/cpuclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuclk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/1/BSTF_CPU_ip/RV-CCCPU.gen/sources_1/ip/cpuclk/cpuclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/1/BSTF_CPU_ip/RV-CCCPU.gen/sources_1/ip/cpuclk/cpuclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/1/BSTF_CPU_ip/RV-CCCPU.srcs/sources_1/ip/cpuclk/cpuclk.xci
# IP: The module: 'cpuclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/1/BSTF_CPU_ip/RV-CCCPU.gen/sources_1/ip/cpuclk/cpuclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/1/BSTF_CPU_ip/RV-CCCPU.gen/sources_1/ip/cpuclk/cpuclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/1/BSTF_CPU_ip/RV-CCCPU.gen/sources_1/ip/cpuclk/cpuclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
