# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/20208/vivado temp/RV-CCCPU/RV-CCCPU.srcs/sources_1/ip/Inst_mem/Inst_mem.xci
# IP: The module: 'Inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/20208/vivado temp/RV-CCCPU/RV-CCCPU.gen/sources_1/ip/Inst_mem/Inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/20208/vivado temp/RV-CCCPU/RV-CCCPU.srcs/sources_1/ip/Inst_mem/Inst_mem.xci
# IP: The module: 'Inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/20208/vivado temp/RV-CCCPU/RV-CCCPU.gen/sources_1/ip/Inst_mem/Inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
